### ISSUE TITLE
How convert double to Decimal from JSON

### ISSUE THREAD

**Issue by spaquis** [a14n/dart-decimal#101]
Hi,
Thanks for you library, i have a problem with the case below : 

```
  const value = 934815969.69241506;
  print(value.toString()); // 934815969.6924151
  
  => Expected Result // 934815969.69241506
```

I have an interface contract, that return the JSON with my value in type double : 
```
{
   ...,
   value: 934815969.69241506
}
```

If i convert this value in string, I lose precision when my value has more than 6/7 digits. This is why I want to handle decimals at the start of the process. I don't find a way to convert a double to Decimal so i don't know how i can solve this probleM.

Thanks in advance for your help ? I may have forgotten something.

**Comment by a14n** [comment]
As you guest double type is not good type to carry decimal values. Generally string is the type used for dealing with decimals in apis.

**Comment by spaquis** [comment]
Ok thanks for your answer
