### ISSUE TITLE
Incorrect Decimal Formatting in Dart code

### ISSUE THREAD

**Issue by vasanthmn1** [a14n/dart-decimal#102]
``` 
import 'package:decimal/decimal.dart';

Decimal formatDecimal(Decimal value) {
  String formattedString = value.toStringAsFixed(2);
  return Decimal.parse(formattedString);
}

void main() {
  Decimal decimalValue = Decimal.parse('8');
  Decimal formattedValue = formatDecimal(decimalValue);
  
  print(formattedValue); // Output: 8.00
}
```
The expected output of the print statement is 8.00 in Decimal format, but the actual output is 8. It seems that the formatting is not being applied correctly.

Could someone please advise on how to correctly format the Decimal value 8 to 8.00 in Dart?

**Comment by a14n** [comment]
I'm not sure to understand what your code is supposed to do but if you have a Decimal `d` (eg. created with `Decimal.parse('8')`) you can simply call `d.toStringAsFixed(2)` to get a String `8.00`.
