### ISSUE TITLE
Add operators for Rational values

### ISSUE THREAD

**Issue by ralf-vogel** [a14n/dart-decimal#103]
When performing calculations with `Rational` values, we can end up with unexpected type errors:

```dart
var oneThird = Decimal.one / Decimal.parse("3");
var result = Decimal.parse("3.14") * oneThird;
```

Resulting in 
```shell
 lib/example.dart:109:46: Error: A value of type 'Decimal' can't be assigned to a variable of type 'Rational'.
 - 'Decimal' is from 'package:decimal/decimal.dart' ('.../decimal-2.3.3/lib/decimal.dart').
 - 'Rational' is from 'package:rational/rational.dart' ('.../rational-2.2.2/lib/rational.dart').
      newValue = basis.value!.toRational() * rateInPercent;
                                             ^
```

The type error is caused by `oneThird`, because it is `Rational`, as expected. So a developer might be intrigued to satisfy the compiler by writing:
```dart
Decimal.parse("3.14") * oneThird.toDecimal();
```
Now everything is decimal again, the compiler is happy and the damage is done. Precision is lost.

The actual solution would be to cast the fist factor:
```dart
Decimal.parse("3.14").toRational() * oneThird;
```
but that seems counter-intuitive at first.

To avoid that mistake, I think the developer should not have to cast at all.
What do you think of rewriting the operators to something like this?
```dart
/// Multiplication operator.
Rational operator *(dynamic other) {
  if (other is Decimal) return _rational * other._rational;
  if (other is Rational) return _rational * other;
  if (other is int) return _rational * Rational.fromInt(other);
  return _rational * Rational.parse(other.toString());
}
```
If the return type `Decimal` should be kept, it could be something like:
```dart
/// Multiplication operator.
Decimal operator *(dynamic other) {
  if (other is Decimal) return (_rational * other._rational).toDecimal();
  if (other is Rational) return (_rational * other).toDecimal();
  if (other is int) return (_rational * Rational.fromInt(other)).toDecimal();
  return (_rational * Rational.parse(other.toString())).toDecimal();
}
```

**Comment by a14n** [comment]
First `oneThird.toDecimal()` doesn't loose precision, it throws an AssertionError because oneThird doesn't have finite precision.

I really don't want to have dynamic type on parameter. This makes the analyzer useless and degrades developer experience. If one day Dart has Union type or operator overloading I'll reconsider allowing int, Bigint, Rational as parameter types on several methods. But for now I prefer to avoid handling directly other types.
