### ISSUE TITLE
Pub cannot resolve dependency

### ISSUE THREAD

**Issue by decapo01** [a14n/dart-decimal#15]
When attempting to get this package I receive the following error

`Package decimal has no versions that match >=0.2.0 <0.3.0 derived from:`

**Comment by zoechi** [comment]
What Dart version are you using? For `decimal: ^0.2.0`
you need Dart 2 https://github.com/a14n/dart-decimal/blob/master/pubspec.yaml#L7

**Comment by a14n** [comment]
Indeed if you're using Dart 1.x you have to use an older version (`^0.1.4`).

Dart 1 has infinite-precision integers. With Dart 2.0, integers in the VM will be 64 bit integers, and not arbitrary-sized anymore.

Starting from `decimal-0.2.0` the package requires Dart-2 [BigInt](https://api.dartlang.org/dev/2.0.0-dev.53.0/dart-core/BigInt-class.html).
