### ISSUE TITLE
Decimal.tryParse("0.9360953686036907").toDouble()

### ISSUE THREAD

**Issue by modulovalue** [a14n/dart-decimal#18]
```
var s = "0.9360953686036907";
expect(double.tryParse(s), 0.9360953686036907); // passes
expect(double.tryParse(s).toString(), s); // passes
expect(Decimal.tryParse(s).toString(), s); // passes
expect(Decimal.tryParse(s).toDouble(), 0.9360953686036907); // fails
```

I think this is not the expected behavior or is it?

**Comment by a14n** [comment]
It works as intended. `Decimal` are backed on `Rational` and may loose precision when converted back to double. In your case `toDouble()` is the result of `BigInt.parse('9360953686036907') / BigInt.parse('10000000000000000')` that gives `0.9360953686036908`.
