### ISSUE TITLE
Specifying precision messes up results?

### ISSUE THREAD

**Issue by davidfaulks** [a14n/dart-decimal#19]
`var dec1 = Decimal.parse("0.256");
var dec2 = dec1 + dec1;
print(dec2.toString());
print(dec2.toStringAsPrecision(20));`
prints
I/flutter ( 5329): 0.512
I/flutter ( 5329): 0.51200000000000001066
in the console. I do not think this is correct behaviour for a Decimal type.

**Comment by a14n** [comment]
This should be fix with `rational-0.3.2` (please upgrade this dep)
