### ISSUE TITLE
unexpected signum value

### ISSUE THREAD

**Issue by davidfaulks** [a14n/dart-decimal#21]
`var dec1 = Decimal.parse("99999999999993.256");
print("num: ${dec1.toString()} signum: ${dec1.signum}");`

prints

`I/flutter ( 6047): num: 99999999999993.256 signum: 2`
This does not match the docs (or the usual definition of signum).

**Comment by a14n** [comment]
Please upgrade to get package `rational-0.3.3` that fixes the issue.

Thanks for repporting.
