### ISSUE TITLE
Changelog does not match pub

### ISSUE THREAD

**Issue by alanhzhao** [a14n/dart-decimal#25]
Pub is on 0.3.5
https://pub.dev/packages/decimal#-changelog-tab-

But the repo here is still on 0.3.4
https://github.com/a14n/dart-decimal/commit/426d5402379f929fd5c3988d5a16f1a3f9e89c83

Can you update the changelog to be consistent?

**Comment by a14n** [comment]
Fixed. Thanks for noticing it.
