### ISSUE TITLE
Problem with toStringAsPrecision

### ISSUE THREAD

**Issue by giorgiofran** [a14n/dart-decimal#26]
The toStringAsPrecision() method, returns a value that differs from num one.
Example:
```
import 'package:decimal/decimal.dart';

void main() {
  Decimal d = Decimal.fromInt(20);
  const num number = 20;
  const int precision = 1;

  print(d.toStringAsPrecision(precision));
  print(number.toStringAsPrecision(precision));
}
```

The result for this example is:
20
2e+1

**Comment by a14n** [comment]
This is working as intended.

There are no garanties that`Decimal.toStringAsPrecision` returns exactly the same String as `num.toStringAsPrecision`. The `Decimal` version of `toStringAsPrecision` will never use exponential representation.
In this particular case `20` looks really better to me than `2e+1`.
