### ISSUE TITLE
Add toJson method

### ISSUE THREAD

**Issue by jonathantribouharet** [a14n/dart-decimal#29]
Hi,
is it possible to add a `toJson` method?
something like:

```
String toJson() => this.toString();
```

It will be very helpful to work with `dart:convert` and automatically convert Decimal to String for generating JSON.
More info here: https://api.dartlang.org/stable/2.6.1/dart-convert/JsonCodec/encode.html

Thanks.

**Comment by a14n** [comment]
Thanks for the idea. Unfortunately I don't think it's correct to convert it directly into a `String`(there's no equivalent type in Javascript to this Decimal object). The two sides (serializer and deserializer) should agree on a way to echange this `Decimal` object (perhaps `decimal: {value: '123432432.12314'}`) and it's not something that can be done in this package.

For a similar case there's no `.toJson()` on [BigInt](https://api.dartlang.org/stable/2.7.0/dart-core/BigInt-class.html).

**Comment by jonathantribouharet** [comment]
From experience decimal are always pass as string in JSON.
I use [dio](https://pub.dev/packages/dio) package for making HTTP requests and it relies on `dart:convert`, I try to add the method with the new extension system from dart 2.7 but it didn't seem to work.

**Comment by a14n** [comment]
>From experience decimal are always pass as string in JSON.

Using String is definitely reliable to encode Decimal. But there must be a special workflow on the receiver to convert this String back to a Decimal. 

>I try to add the method with the new extension system from dart 2.7 but it didn't seem to work.

It will not work because the extension methods work on explicit call from source.

To support your use case you have to make a specific `.toJson()` on every class having a Decimal field.

```dart
class MyClass {
  Decimal value;
  Map<String, Object> toJson() => {
    'value': value?.toString(),
  }
}
```
