### ISSUE TITLE
Please add:  static Decimal negativeone = Decimal.fromInt(-1);

### ISSUE THREAD

**Issue by codegrue** [a14n/dart-decimal#31]

**Comment by a14n** [comment]
`Decimal.negativeone` (or `Decimal.negativeOne`) doesn't look better than `-Decimal.one` in my opinion.

Similarly the [BigInt](https://api.dart.dev/stable/2.7.1/dart-core/BigInt-class.html) doesn't have such value as static property.

**Comment by codegrue** [comment]
Thanks didn't know that would work.
