### ISSUE TITLE
Square root?

### ISSUE THREAD

**Issue by wdavies973** [a14n/dart-decimal#36]
Would be useful to have a function `.sqrt()` that takes the square root of the `Decimal`.
Bonus points for `nroot(double n)` that takes the nth root.

Also, could you add a new constructor called `Decimal.fromDouble(double d)` for instantiating `Decimal`'s from doubles?

Thanks!

**Comment by a14n** [comment]
> Would be useful to have a function .sqrt() that takes the square root of the Decimal.

Square roots are not guaranteed to be Decimal numbers. So it's hard to argue that this function should be added. For instance what Decimal should return `Decimal.fromInt(2).sqrt()`?

> could you add a new constructor called Decimal.fromDouble(double d) for instantiating Decimal's from doubles?

See #27
