### ISSUE TITLE
Exponent restriction on Decimal.pow/Rational.pow seems unnecessary

### ISSUE THREAD

**Issue by jamesderlin** [a14n/dart-decimal#44]
The documentation for `Decimal.pow` and `Rational.pow` states:

> Returns one if the exponent equals 0.
>
> The exponent must otherwise be positive.

The requirement for a non-negative exponent seems unnecessary since they could easily return the reciprocal for negative values.  Arguably callers could easily do that themselves too, but it's inconvenient, and it's inconsistent with [`pow`](https://api.dart.dev/stable/dart-math/pow.html) from `dart:math`.

**Comment by a14n** [comment]
Fixed via https://github.com/a14n/dart-decimal/commit/ce00543b01dcbb892c89c8590a1e386be509f6f6 and https://github.com/a14n/dart-rational/commit/605ae4c59fe78e863e362603bb48ffd9fa97307a. Released in 1.1.0.
