### ISSUE TITLE
Converting incoming json numerics

### ISSUE THREAD

**Issue by IanWorthington** [a14n/dart-decimal#45]
I have some financial data passed to me in json format.  Unfortunately there seems no way to tell dart's json parser to not convert numeric strings to double (or int) if they can be successfully parsed that way (I think: I haven't yet found the internals).

I'm thinking then that the next best thing is to stringify them as soon as I can get hold of them, truncate them to 15* significant digits, or at least any decimal places after 15 sds, maybe, and then pass that to Decimal.parse().

I'd be interested to know what other people are doing about converting incoming json numerics.

* 15 being the guaranteed precision of an ieee binary64 fp.

**Comment by a14n** [comment]
Some explanations and advices can be grabbed at https://stackoverflow.com/questions/35709595/why-would-you-use-a-string-in-json-to-represent-a-decimal-number

**Comment by IanWorthington** [comment]
@a14n Thanks for that link Alexandre, must appreciated and very interesting.  I nearly fell down the Dragon4 rabbit hole, but just about stopped myself in time.

I'm unsure of how best to procede on this.  Doing it right from a double is clearly a labour of love with minimal return.  It would be far better to spend the time on disembowelling the json parser to get a String out of the damn thing.

I've raised an issue on the dart-lang github (https://github.com/dart-lang/sdk/issues/45856), which you may wish to contribute your own expertise to? (It feels rather like Dart is a young language and they're making many of the same mistakes that Java made as they clip along, though without Gosling's hubris.)

**Comment by a14n** [comment]
If you control the server data I'd recommand to use String in your json and transform the value to decimal after `json.decode` (thus the implementation can use native json parser provided by the underlying plateform directly without hack). JSON numbers are not really suited for financial usage where your shouldn't loose precision.

**Comment by IanWorthington** [comment]
> If you control the server data I'd recommand to use String in your json and transform the value to decimal after `json.decode` (thus the implementation can use native json parser provided by the underlying plateform directly without hack). JSON numbers are not really suited for financial usage where your shouldn't loose precision.

Indeed.  Regrettably, I don't control the server data and they send it in numeric format.  So I'm looking for the best solution for that.
