### ISSUE TITLE
Freezes while parsing a number that is too big

### ISSUE THREAD

**Issue by canastro** [a14n/dart-decimal#47]
**Given** `value = 6E739019`
**When** `Decimal.tryParse(value);`
**Then** It takes a long time, the computer fans start spinning
**Expected** I was expecting to fail, but I was expecting to fail "faster" and with .isInifinte as true. 

In my specific case I only want to support numbers until [1.79769E+308](https://spreadsheetpoint.com/google-sheets-limitations/#Maximum_Value_allowed_in_a_cell_in_Google_Sheets_-_179769E308). Is there any way I can handle this on my side?

**Comment by a14n** [comment]
This issue should be fixed by https://github.com/a14n/dart-rational/commit/82c4c987ffb1aabcb5f4a9129c4f85b01f11f966 .

Please upgrade your dependencies to get rational-1.2.0 and the issue should be resolved.

**Comment by canastro** [comment]
Much better, thanks 💪🏽 

PS: Also, while trying to debug why it was so slow I did a "print(value)" which made things worse 😅

**Comment by a14n** [comment]
The problem with `print(value)` is more complicated. I filed dart-lang/sdk#46179 and  dart-lang/sdk#46180 .

Closing this issue as the initial subject is fixed.
