### ISSUE TITLE
toStringAsExponential returns INFINITY

### ISSUE THREAD

**Issue by canastro** [a14n/dart-decimal#48]
**Given**: `value = Decimal.parse('1.7976931348623157e+310')`
**When**: `value.toStringAsExponential(10)`
**Then**: `Infinity`
**Expected**: In my specific Use case I was expecting `Decimal.parse('1.7976931348623157e+310').isInfinite` to be true, but I guess that  if the `toStringAsExponential(10)` returned `1.7976931348e+310` that would be expected as well.

PS: the limit seems to be `Decimal.parse('1.7976931348623158e+308').toStringAsExponential(10)`

**Comment by a14n** [comment]
For now `toStringAsExponential` relays on `double.toStringAsExponential` and is limited to `double.maxFinite` (1.7976931348623157e+308)

**Comment by canastro** [comment]
Thanks for your quick answers!

For the time being that limit is actually ok for my use-case. Feel free to close it if you want or to leave it open if you feel that this is something that this lib will be able to handle.

**Comment by a14n** [comment]
Fixed in 2.1.0
