### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by Bunny1376** [a14n/dart-decimal#49]
hey, i am using decimal version 1.1.0
i want to divide 100,000 to 63,149,175
what i expected is : 0.001583551962476
what i get is : 0.001583552
what is wrong in my code? i set all numbers as Decimal numbers

**Comment by a14n** [comment]
`100000/63149175` has not a finite precision. The default behaviour in this case is to output 10 fraction digits. That why you get `0.001583552`.

```dart
Decimal dec(String value) => Decimal.parse(value);

print((dec('100000')/dec('63149175')).toString());            // 0.001583552
print((dec('100000')/dec('63149175')).toStringAsFixed(10));   // 0.0015835520
print((dec('100000')/dec('63149175')).toStringAsFixed(20));   // 0.00158355196247615270
print((dec('100000')/dec('63149175')).toStringAsFixed(30));   // 0.001583551962476152697165085688
```
