### ISSUE TITLE
Allow parsing with Intl format

### ISSUE THREAD

**Issue by kuhnroyal** [a14n/dart-decimal#52]
It would be great if it would be possible to parse a string into a decimal with a configurable `NumberFormat`, `Locale` or `Symbols` set.

This would allow parsing a locale-specific string. Currently I have to go with `NumberFormat.parse` which parses to a double and has a limited length.

**Comment by anqit** [comment]
making an attempt at allowing this more easily [here](https://github.com/dart-lang/i18n/pull/686)

**Comment by anqit** [comment]
created a PR for this, any way to get it looked at/merged?

**Comment by a14n** [comment]
A new `DecimalFormatter` is now available on `decimal-3.0.0`. See https://pub.dev/packages/decimal#parsing-with-intl.
Thanks @anqit for your contribution.
