### ISSUE TITLE
No way to get the fractional part

### ISSUE THREAD

**Issue by pryshrm** [a14n/dart-decimal#58]
I find it very weird that it has precision, scale, and truncate but has no method that returns the fractional part as int.

**Comment by a14n** [comment]
A _fractional part as int_ doesn't make a lot of sense to me. What should be the fractional part of `1.2`, `1.02`, `1.0002`?

Note that you can get the decimal part of a Decimal `d` with `d % Decimal.one` (`0.02` for `d = Decimal.parse('1.02')`).

**Comment by pryshrm** [comment]
You are right. 0002 as int doesn't make any sense.

Actually, I am using Decimal for monetary values and I was checking out money2 package for the same purpose because it allows me to apply currency and locale as well. But money2 package doesn't give me any way to get Money from a Decimal value. I was just trying to figure out an efficient way to covert Decimal into Money and thought that if I could split Decimal into dollars and cents, that would be good. But, as you pointed out, 0002 throws that strategy off.

thanks for responding!

**Comment by pryshrm** [comment]
In case, anyone comes looking for something similar, here is what I am doing now:

```
  Decimal amount = Decimal.parse('101.02');
  Decimal HUNDRED = Decimal.fromInt(100);
  String cents = (amount*HUNDRED).toString();
  BigInt bi = BigInt.parse(cents);
  Money m = Money.fromBigInt(bi, code:'USD');
  print(m); // prints $101.02

```

**Comment by a14n** [comment]
I don't know the money2 package but having a quick look, why don't you use :

```dart
var amount = Decimal.parse('101.02');
var m = Money.parse(amount.toString(), code:'USD');
```

**Comment by pryshrm** [comment]
Money.parse(amount.toString(), code:'USD'); doesn't work, unfortunately.

**Comment by a14n** [comment]
`var m = Money.parse(r'$' + amount.toString(), code: 'USD');` should work.

**Comment by a14n** [comment]
I agree and I really don't understand why this leading $ is needed as you have to specify the code. @bsutton WDYT?

**Comment by bsutton** [comment]
So the issues is that you are using the default pattern for 'USD' which is taken from the CommonCurrencies class.

You can specify an alternate pattern that doesn't require the $.

var m = (Money.parse('1,000.25', code: 'USD', pattern: '#.#');

I think it does raise the question as to whether the parser should allow elements such as the currency to be optional.

If we made the S and the CCC optional then the following would all work without having to specify alternate patterns.
var m = (Money.parse('1,000.25', code: 'USD', pattern: 'SCCC#.#');
var m = (Money.parse('$1,000.25', code: 'USD', pattern: 'SCCC#.#');
var m = (Money.parse('$USD1,000.25', code: 'USD', pattern: 'SCCC#.#');

Can you think any reason why this might be detrimental?

**Comment by pryshrm** [comment]
As of now, the only reason I am using Money is because I can use Text(money.toString()); and it would show the amount in a nicely formatted manner with currency symbol, commas and stuff, taking into account the currency and locale. (Without me worrying about about symbols and patterns. I am happy with the defaults.)

I am using Decimal instead of double because the application performs mathematical operations on amount. So, ideally, if Money had a constructor that took a Decimal and the currency code, that would have been perfect. 

Both Decimal and Money packages are actually very good. The problem is that there is no standard data type for monetary values in Dart. May be it was an unwitting omission in Java but I don't understand why this lacuna exists and continues to remain unaddressed in Dart even though a HUGE number of applications deal with money!

**Comment by pryshrm** [comment]
BTW @bsutton, will pattern: '#.#' work for all currencies? What about the comma in '1,000.25'? That is not in the pattern. 
I think Money.parse('1000.25', code: 'GBP', pattern: '#.#'); will work equally well. Will check it out.
thanks for the suggestion.

**Comment by pryshrm** [comment]
>Can you think any reason why this might be detrimental?
Too many moving parts.

**Comment by bsutton** [comment]
Too many moving parts?

**Comment by bsutton** [comment]
Not at my desk but I think the commas are already optional.

**Comment by bsutton** [comment]
So why aren't you just using Money to store your money?

**Comment by pryshrm** [comment]
Yes, I think I will.
