### ISSUE TITLE
Add `toJson` in order to make `Decimal` encodable

### ISSUE THREAD

**Issue by AlexV525** [a14n/dart-decimal#59]
## Related issues
- #29 
- #55 

## Summary
`Decimal` didn't have encodable support yet, and these issues addressed the most straightforward part of it, making it a `String`.
As far as I can imagine, we can have some flags when implementing the `toJson` method, to make it more flexible.
A fallback behavior can make less code when involved with conversions.

## Proposal
In real-time development, services often accept both string and number when handling decimals though there are no rules for this. So a possible solution that covers both number and string can be like:

```dart
Object toJson({bool toString = true}) {
  if (toString) return toString();
  return num.parse(this);
}
```

Let me know if you have more thoughts about this.

**Comment by a14n** [comment]
Thanks for your proposal/feedback.

I think a `toJson()` method would be 99% of time called from dart:convert when a user need to serialize an object tree. In this case this optional parameter will never be provided.

That said and regarding the number of issue asking for it I may consider to reopen #55 to add a default toJson/fromJson with a String encoding for Decimal.

**Comment by AlexV525** [comment]
> add a default toJson/fromJson with a String encoding for Decimal.

SGTM. Numbers can be converted using specific parsers like `int.parse`, `double.parse`, or `num.parse`. Not only do they require a string, but a string is more suitable for logs and other things IMO.

**Comment by AlexV525** [comment]
@a14n As the constructor tear-off is supported on stable, I've tried to use `@JsonKey(fromJson: Decimal.fromJson)` as annotation, but it seems to run into failure.
```
[SEVERE] json_serializable:json_serializable on lib/models/data_model.dart:

Unsupported operation: Not sure how to support typeof ConstructorElementImpl
[INFO] Running build completed, took 11.4s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 47ms

[SEVERE] Failed after 11.4s
```
![image](https://user-images.githubusercontent.com/15884415/182762241-f88e1235-bfbc-4620-aa42-2b7ced621dff.png)

Use `@JsonKey(fromJson: _decimalFromJson)` is fine as usual.

**Comment by a14n** [comment]
This error looks related to the `json_serializable` generator.
