### ISSUE TITLE
Rounding off to two or n decimal places

### ISSUE THREAD

**Issue by pryshrm** [a14n/dart-decimal#64]
Decimal d = Decimal.fromInt(200)/Decimal.fromInt(3); //assigns 66.6666666667 to d.
d =  d.round(); //assigns 67

It would be very useful to have a round(int precision) method that would assign 66.67 to d:
d = d.round(2)?

If that is not possible, how can the same be achieved using the existing API?

**Comment by a14n** [comment]
With the existing API you can do:

```dart
Decimal roundAt(Decimal decimal, int scale) {
  final scaleFactor = Decimal.ten.pow(scale);
  return (decimal * scaleFactor).round() / scaleFactor;
}
```

I will take if this can be introduce in the existing API. Thanks for the idea.

**Comment by a14n** [comment]
Starting from decimal-2.0.0 you can do `d.round(scale: 2)`

**Comment by pryshrm** [comment]
wow!
Thanks a lot!!
