### ISSUE TITLE
Feature request: math expression parse.

### ISSUE THREAD

**Issue by cnmade** [a14n/dart-decimal#68]
How to parse a input math expression string?

like 
```
7*1.05/4.3923+1.1716*0.31825
```

**Comment by a14n** [comment]
Parsing math expressions is not the purpose of this library. Its only goal is to avoid loosing precision on decimal operations.

You have to find another package to parse math expression or implement it yourself. [petitparser](https://pub.dev/packages/petitparser#writing-a-more-complicated-grammar) could help.
