### ISSUE TITLE
Undefined name 'NumberFormat'.

### ISSUE THREAD

**Issue by vvvadadda** [a14n/dart-decimal#72]
Undefined name 'NumberFormat'.
Try correcting the name to one that is defined, or defining the name.dart[undefined_identifier](https://dart.dev/diagnostics/undefined_identifier)

**Comment by a14n** [comment]
`NumberFormat` comes from the [intl](https://pub.dev/packages/intl) package. You need to add the following import:

```dart
import 'package:intl/intl.dart';
```
