### ISSUE TITLE
Different results from toStringAsExponential in double and in decimal

### ISSUE THREAD

**Issue by canastro** [a14n/dart-decimal#74]
A few releases Decimal was using Doubles to perform `toStringAsExponential`:
```dart
toDouble().toStringAsExponential(fractionDigits); 
```

This approach seems to use the [normalized scientific notation](https://en.wikipedia.org/wiki/Scientific_notation#:~:text=In%20normalized%20scientific%20notation%20(called%20%22standard%20form%22%20in%20the%20UK)%2C%20the%20exponent%20n%20is%20chosen%20so%20that%20the%20absolute%20value%20of%20m%20remains%20at%20least%20one%20but%20less%20than%20ten%20(1%20%E2%89%A4%20%7Cm%7C%20%3C%2010).%20Thus%20350%20is%20written%20as%203.5%C3%97102.), ie: given dec('9.9999e+7').toStringAsExponential(2) it would output 1.00e+8.

With the current implementation that same input will return 10.00e+7.

**Comment by a14n** [comment]
Fix available in 2.2.0
