### ISSUE TITLE
Removal of isNegative broke NumberFormat

### ISSUE THREAD

**Issue by mwawrusch** [a14n/dart-decimal#79]
Using a NumberFormat to format a decimal stopped working after version 1.5 because isNegative got removed. Now it needs to be converted to a double before formatting. Not a biggie per se, but something that could warrant mentioning in the docs.

**Comment by a14n** [comment]
There is a [test](https://github.com/a14n/dart-decimal/blob/cbfc0a198d30a3eb4860f22357bc1281d2955ae9/test/intl_test.dart) that succeeds for `NumberFormat`.

Can you provide the decimal number that failed?
