### ISSUE TITLE
Include benchmarks

### ISSUE THREAD

**Issue by feinstein** [a14n/dart-decimal#82]
It would be nice if we could have a sample benchmark to compare the performance of this package, against using a `double`.

**Comment by a14n** [comment]
Benchmarks usually depend on a lot of things (machine, OS, sdk, versions....) and should rather be considered at your project level.
 
If I wanted to add benchmarks (that is likely not going to happen) what should be tested : which operations, which numbers, which combinations...?

Finally choosing between `Decimal` vs. `double` should mainly be driven by the requirement to loose precision. If it is acceptable to loose precision and you have some perf requirements, go with double first, make some mesures then replace with Decimal and compare. If the delta is "acceptable" go with Decimal to avoid loosing precision.
