### ISSUE TITLE
Default scaleOnInfinitePrecision value on toDecimal()

### ISSUE THREAD

**Issue by giorgiofran** [a14n/dart-decimal#84]
Trying to use `toDecimal() ` on a Rational with infinite precision throws an Assertion error.
This is annoying because you have always, for security reason, provide a `scaleOnInfinitPrecision` value, especially when you are managing the result of a division.
It would be possible to avoid this setting a default value for the `scaleOnInfinitePrecision `parameter?
Something like this:
```dart
 Decimal toDecimal({int? scaleOnInfinitePrecision = 10}) {
    if (hasFinitePrecision) {
      return Decimal._(this);
    }
    final scaleFactor = _r10.pow(scaleOnInfinitePrecision);
    return Decimal._(
        (this * scaleFactor).truncate().toRational() / scaleFactor);
  }
```

**Comment by giorgiofran** [comment]
One more question, wouldn't it be more precise to use round() instead of truncate() in toDecimal()?
Example:
```dart
 return Decimal._( (this * scaleFactor).round().toRational() / scaleFactor);
```

**Comment by a14n** [comment]
> setting a default value for the scaleOnInfinitePrecision parameter?

This conversion may loses precision and I prefer the user is forced to handle that explicitly rather than relaying on an arbitrary value (why 10, 2 or something else as default?). At some point I even evaluate the option to make the parameter required but it was not really user-friendly for operations known to return a finite number. 

> wouldn't it be more precise to use round() instead of truncate() in toDecimal()?

Good call. I need to think about the implications.

**Comment by giorgiofran** [comment]
Last observation.
We have the same problem in the `pow()` method, but here we cannot specify `scaleOnInfinitePrecision` parameter.
For example, try the following:
```dart
Decimal.fromInt(3).pow(-2);
```

**Comment by a14n** [comment]
Ooops, `pow` should definitelly be change by either requiring a non-negative parameter or by returning a `Rational`. I tend to prefer the former solution.

**Comment by a14n** [comment]
> wouldn't it be more precise to use round() instead of truncate() in toDecimal()?

For now I'm going to leave the code unchanged. The doc of `toDecimal()` mentions : _`scaleOnInfinitePrecision` can be provided to truncate its decimal representation_. So it is consistent. In a next major release I may revisit the Rational to Decimal conversion.

Thanks for your suggestions.

**Comment by a14n** [comment]
> Ooops, pow should definitelly be changed by either requiring a non-negative parameter or by returning a Rational. I tend to prefer the former solution.

Finally returning a Rational looks more consistant with the other methods that can return a Rational (like `/` and others). Unfortunately it's a breaking change.

**Comment by a14n** [comment]
Just upload 2.3.0 that contains the result of this thread.
