### ISSUE TITLE
V 2.3.0 Throw Failed assertion: line 27 pos 38: '_rational.hasFinitePrecision': is not true.

### ISSUE THREAD

**Issue by kecson** [a14n/dart-decimal#85]
code sample:

  var rational = (Decimal.one / Decimal.fromInt(3)).toDecimal();
  print(rational);

error: 'package:decimal/decimal.dart': Failed assertion: line 27 pos 38: '_rational.hasFinitePrecision': is not true.

**Comment by a14n** [comment]
When you convert a `Rational` (you're not in control or known to not have a finite precision like `1/3`) to a `Decimal` you have to specify what precision should be use with `scaleOnInfinitePrecision` named parameter.

```dart
var rational = (Decimal.one / Decimal.fromInt(3)).toDecimal(scaleOnInfinitePrecision: 2);
print(rational); // 0.33
```

Starting from [2.0.0](https://pub.dev/packages/decimal/changelog#200-2021-11-29) a Decimal must always have a finite precision.
