### ISSUE TITLE
Error: A value of type 'Rational' can't be assigned to a variable of type 'Decimal'.

### ISSUE THREAD

**Issue by bsutton** [a14n/dart-decimal#88]
I've had a bug reported against the money2 package which appears to stem from the latest upgrade to decimal 2.3.0 and the breaking change to pow.

https://github.com/onepub-dev/money.dart/issues/70

The error is:

```
Failed to load "test/rounding_test.dart":
test/rounding_test.dart:1
: Error: A value of type 'Rational' can't be assigned to a variable of type 'Decimal'.
../…/src/fixed.dart:97
- 'Rational' is from 'package:rational/rational.dart' ('../../.pub-cache/hosted/pub.dartlang.org/rational-2.2.0/lib/rational.dart').
package:rational/rational.dart:1
- 'Decimal' is from 'package:decimal/decimal.dart' ('../../.pub-cache/hosted/pub.dartlang.org/decimal-2.3.0/lib/decimal.dart').
package:decimal/decimal.dart:1
      (amount * Decimal.ten.pow(amount.scale)).toBigInt(),
```

Overriding  the decimal dependency back to 2.2.0 resolves the issue.

You can reproduce the issue by cloning the latest version of money2 and attempt to run the money2 unit tests.

If you are using a version of dart prior to 2.18 you need to change the hard_lint dependency back to 1.0.0.

**Comment by a14n** [comment]
Sorry about the breaking change on `.pow` but it was required to make methods consistent about return types. I sent https://github.com/onepub-dev/fixed/pull/9 to fix your `fixed` package.
