### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by gyihasz** [a14n/dart-decimal#91]
Hi Alexandre, 

I wanted to ask you to consider setting the license up properly in `pub.dev`, because it displays "unknown", even though I can see that this package is licensed under Apache 2.0.

Due to this missing license setting in `pub.dev`, this package is being reported by our license checker.

**Comment by a14n** [comment]
Thanks for your report. I updated the LICENSE file in 9b05cd026c6589acc5fc51d53b8a9a4ca1a3d4ec and published a new version. Now in `decimal-2.3.1` Apache license is correctly detected.
