### ISSUE TITLE
Decimal.pow(Decimal) return Rational instead of Decimal

### ISSUE THREAD

**Issue by joranmulderij** [a14n/dart-decimal#92]
`Decimal.pow(Decimal)` return `Rational` instead of `Decimal`. Is there any reason for this? I know you can append the expression with `.toDecimal()`, but it seems inconsistent. The same is the case for normal division, which also returns a `Rational`.

**Comment by a14n** [comment]
A Rational is returned because sometimes you can end up with something that is not a Decimal (e.g`dec('3').pow(-1)`).
