### ISSUE TITLE
Formatting with many decimals returns incorrect string

### ISSUE THREAD

**Issue by i4guar** [a14n/dart-decimal#96]
As a context for crypto currencies I need to be able to format decimal numbers with up to 20 decimals.

```
    final decimal = Decimal.fromInt(1000);
    final formatter = NumberFormat(
      "0.0###################",
      "en_US",
    );
    print(formatter.format(DecimalIntl(decimal)));
```

Output:
```
1000.76627963145224192
```

Expected Output:
```
1000.00000000000000000
```

**Comment by a14n** [comment]
The issue is located inside [intl][] because you get the same _incorrect_ result with `print(formatter.format(1000));` (without `decimal` package). Feel free to file an issue on the [intl][] repo.

[intl]: https://github.com/dart-lang/intl
